version: 2

sources:
    - name: COVID19_Epidemiological_Data
      description: 'This is a test.'
      database: COVID19_Epidemiological_Data
      schema: PUBLIC
      tables:
        - name: DEMOGRAPHICS
          description: 'This is a test.'